---
- name: "[{{ svc_name }}] Создаём секрет"
  vars:
    envFile: "{{ lookup('file', svc_name + '/.env') }}"
  community.docker.docker_secret:
    name: "{{ svc_name }}.env"
    data: "{{ envFile | b64encode }}"
    labels:
      secret: "{{ envFile | hash('sha1') }}"
    data_is_b64: true
    state: present