---
- name: "[{{ svc_name }}] Создаём секрет"
  vars:
    env_file: "{{ lookup('template', svc_name + '/.env.j2') }}"
  community.docker.docker_secret:
    name: "{{ svc_name }}.env"
    data: "{{ env_file | b64encode }}"
    labels:
      secret: "{{ env_file | hash('sha1') }}"
    data_is_b64: true
    state: present