---
- name: "[{{ svc_name }}] Конфигурация секрета"
  block:
    - name: "[{{ svc_name }}] Создаём секрет"
      ansible.builtin.include_tasks: "secret-create.yml"
  tags: "{{ svc_name }}"
  
  rescue:
    - name: "[{{ svc_name }}] Удаляем сервис"
      community.docker.docker_swarm_service:
        name: "{{ svc_name }}"
        state: absent 
      
    - name: "[{{ svc_name }}] Создаём секрет"
      ansible.builtin.include_tasks: "secret-create.yml"